export const sectors = [
  { code: "automotive", value: "Automotive" },
  { code: "beauty_spa_salon", value: "Beauty, Spa and Salon" },
  { code: "clothing_apparel", value: "Clothing and Apparel" },
  { code: "education", value: "Education" },
  { code: "entertainment", value: "Entertainment" },
  { code: "event_planning_service", value: "Event Planning and Service" },
  { code: "finance_banking", value: "Finance and Banking" },
  { code: "food_grocery", value: "Food and Grocery" },
  { code: "public_service", value: "Public Service" },
  { code: "hotel_lodging", value: "Hotel and Lodging" },
  { code: "medical_health", value: "Medical and Health" },
  { code: "non_profit", value: "Non-profit" },
  { code: "professional_services", value: "Professional Services" },
  { code: "shopping_retail", value: "Shopping and Retail" },
  { code: "travel_transportation", value: "Travel and Transportation" },
  { code: "restaurant", value: "Restaurant" },
  { code: "other", value: "Other" },
];